audience:
  #代表这个JWT的接收对象，存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥，经过Base64加密 ，可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # jwt的签发主体，存入issuer
  name: HuiT
  # 过期时间，时间戳
  expiresSecond: 172800000

server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: abc86557788
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  jpa:
    open-in-view: false

mybatis:
  type-aliases-package: classpath:com.example.demo.entity.*
  mapper-locations: classpath:mapper/*.xml


